from google import genai
from app.config import get_settings
import tempfile
import os
import uuid
import logging
from PIL import Image

logger = logging.getLogger(__name__)
settings = get_settings()

def get_fallback_image() -> str:
    """Create a 1x1 transparent pixel to avoid permission errors on empty paths."""
    temp_dir = tempfile.gettempdir()
    path = os.path.join(temp_dir, "fallback_pixel.png")
    if not os.path.exists(path):
        img = Image.new('RGBA', (1, 1), (0, 0, 0, 0))
        img.save(path)
    return path

async def generate_image(prompt: str) -> str:
    """
    Generate an image using Google Gen AI SDK (v2).
    Returns the absolute path to the generated image file.
    """
    try:
        logger.info(f"[Imagen] Generating image for: {prompt[:100]}...")
        
        # Use separate Imagen key if provided, otherwise fallback to main Google key
        api_key = settings.imagen_api_key or settings.google_api_key
        client = genai.Client(api_key=api_key)
        
        # Call the generation (Imagen 4 is available in this environment)
        response = client.models.generate_images(
            model='imagen-4.0-fast-generate-001',
            prompt=f"A high-quality, illustrative, educational vector-style image of: {prompt}",
            config={
                'number_of_images': 1,
                'aspect_ratio': "1:1"
            }
        )
        
        # Save to temp location
        temp_dir = tempfile.gettempdir()
        image_id = str(uuid.uuid4())[:8]
        image_path = os.path.join(temp_dir, f"imagen_{image_id}.png")
        
        # The response usually contains image objects
        if response.generated_images:
            gen_img = response.generated_images[0]
            
            # Robust extraction of image bytes
            image_bytes = None
            if hasattr(gen_img, 'image_bytes') and gen_img.image_bytes:
                image_bytes = gen_img.image_bytes
            elif hasattr(gen_img, 'image') and hasattr(gen_img.image, 'image_bytes'):
                image_bytes = gen_img.image.image_bytes
            
            if image_bytes:
                import io
                img_data = io.BytesIO(image_bytes)
                img = Image.open(img_data)
                img.save(image_path)
                logger.info(f"[Imagen] Image successfully generated and saved at {image_path}")
                return image_path
            else:
                raise RuntimeError("Could not find image bytes in the generated image object.")
        else:
            raise RuntimeError("No images were generated by the model.")

    except Exception as e:
        logger.error(f"[Imagen] Error generating image: {str(e)}")
        # CRITICAL: Return path to invisible pixel instead of empty string to avoid PermissionError in Manim
        return get_fallback_image()
